# Generated by Django 2.2.4 on 2019-12-23 14:46

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0003_auto_20191219_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('sale_price', otree.db.models.CurrencyField(null=True)),
                ('seller_id', otree.db.models.PositiveIntegerField(choices=[(1, 'Buy from seller 1'), (2, 'Buy from seller 2'), (0, 'Buy nothing')], null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemon_market2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'lemon_market2_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lemon_market2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'lemon_market2_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('seller_proposed_price', otree.db.models.CurrencyField(null=True, verbose_name='Please indicate a price (from 0 to 50) you want to sell')),
                ('seller_proposed_quality', otree.db.models.CurrencyField(choices=[(30, '高品質／High'), (20, '中品質／Medium'), (10, '低品質／Low')], null=True, verbose_name='あなたが生産したい品質の製品を選んで下さい．／Please select a quality grade you want to produce')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lemon_market2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemon_market2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemon_market2_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemon_market2.Subsession')),
            ],
            options={
                'db_table': 'lemon_market2_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemon_market2.Subsession'),
        ),
    ]
