# Generated by Django 2.2.12 on 2021-05-23 05:03

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_gen_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Trust_gen_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trust_gen_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Trust_gen_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('Trust_1', otree.db.models.IntegerField(choices=[[1, '全くそう思わない'], [2, 'そう思わない'], [3, 'どちらかといえばそう思わない'], [4, 'どちらともいえない'], [5, 'どちらかといえばそう思う'], [6, 'そう思う'], [7, '強くそう思う']], null=True, verbose_name='ほとんどの人は基本的に正直である')),
                ('Trust_2', otree.db.models.IntegerField(choices=[[1, '全くそう思わない'], [2, 'そう思わない'], [3, 'どちらかといえばそう思わない'], [4, 'どちらともいえない'], [5, 'どちらかといえばそう思う'], [6, 'そう思う'], [7, '強くそう思う']], null=True, verbose_name='ほとんどの人は信頼できる')),
                ('Trust_3', otree.db.models.IntegerField(choices=[[1, '全くそう思わない'], [2, 'そう思わない'], [3, 'どちらかといえばそう思わない'], [4, 'どちらともいえない'], [5, 'どちらかといえばそう思う'], [6, 'そう思う'], [7, '強くそう思う']], null=True, verbose_name='ほとんどの人は基本的に善良で親切である')),
                ('Trust_4', otree.db.models.IntegerField(choices=[[1, '全くそう思わない'], [2, 'そう思わない'], [3, 'どちらかといえばそう思わない'], [4, 'どちらともいえない'], [5, 'どちらかといえばそう思う'], [6, 'そう思う'], [7, '強くそう思う']], null=True, verbose_name='ほとんどの人は他人を信頼している')),
                ('Trust_5', otree.db.models.IntegerField(choices=[[1, '全くそう思わない'], [2, 'そう思わない'], [3, 'どちらかといえばそう思わない'], [4, 'どちらともいえない'], [5, 'どちらかといえばそう思う'], [6, 'そう思う'], [7, '強くそう思う']], null=True, verbose_name='私は，人を信頼するほうである')),
                ('Trust_gen', otree.db.models.IntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trust_gen.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_gen_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_gen_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trust_gen.Subsession')),
            ],
            options={
                'db_table': 'Trust_gen_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trust_gen.Subsession'),
        ),
    ]
