# Generated by Django 2.2.4 on 2020-02-08 02:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='seller_proposed_quality',
            field=otree.db.models.StringField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=10000, null=True, verbose_name='あなたが生産したい品質の製品を選んでください./Please select a quality grade you want to produce'),
        ),
    ]
