# Generated by Django 2.2.4 on 2020-02-08 05:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0004_auto_20200208_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sale_quality',
            field=otree.db.models.StringField(default='high', max_length=10000, null=True),
        ),
    ]
