# Generated by Django 2.2.4 on 2019-12-21 04:43

from django.db import migrations, models
import django.db.models.deletion
import otree.currency
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0003_auto_20191219_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('strategy', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('amount_offered', otree.db.models.CurrencyField(choices=[(otree.currency.Currency('0'), otree.currency.Currency('0')), (otree.currency.Currency('1'), otree.currency.Currency('1')), (otree.currency.Currency('2'), otree.currency.Currency('2')), (otree.currency.Currency('3'), otree.currency.Currency('3')), (otree.currency.Currency('4'), otree.currency.Currency('4')), (otree.currency.Currency('5'), otree.currency.Currency('5')), (otree.currency.Currency('6'), otree.currency.Currency('6')), (otree.currency.Currency('7'), otree.currency.Currency('7')), (otree.currency.Currency('8'), otree.currency.Currency('8')), (otree.currency.Currency('9'), otree.currency.Currency('9')), (otree.currency.Currency('10'), otree.currency.Currency('10'))], null=True)),
                ('offer_accepted', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_0', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_1', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_2', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_3', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_4', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_5', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_6', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_7', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_8', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_9', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('response_10', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimatum10_group', to='otree.Session')),
            ],
            options={
                'db_table': 'ultimatum10_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimatum10_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'ultimatum10_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ultimatum10.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimatum10_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultimatum10_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatum10.Subsession')),
            ],
            options={
                'db_table': 'ultimatum10_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatum10.Subsession'),
        ),
    ]
