# Generated by Django 2.2.12 on 2021-05-23 05:03

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rei_group', to='otree.Session')),
            ],
            options={
                'db_table': 'REI_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rei_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'REI_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('ratemo_1', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='たいていの人より，ものごとを論理的に解決するのが上手である．')),
                ('ratemo_2', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='直観に頼らなければならない状況は好きではない．')),
                ('ratemo_3', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='自分の予感を信じることにしている．')),
                ('ratemo_4', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='論理的な考えの持ち主だ．')),
                ('ratemo_5', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='ものごとを注意深く理論的に解決するのは，得意ではない．')),
                ('ratemo_6', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常に当てはまる', '非常に当てはまる')], max_length=10000, null=True, verbose_name='簡単な問題より複雑な問題の方が好きだ．')),
                ('ratemo_7', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='なぜだか理由を説明できないが，その人が正しいか間違っているかを，感じとることができる．')),
                ('ratemo_8', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常に当てはまる', '非常に当てはまる')], max_length=10000, null=True, verbose_name='分析的に考える方ではない．')),
                ('ratemo_9', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='私にはすごい直観力はない．')),
                ('ratemo_10', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='考えることは，楽しいことだと思わない．')),
                ('ratemo_11', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='直観は問題を解決するのに役立つ方法だろう．')),
                ('ratemo_12', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='感情に基づいて重要な決定をするのは，愚かなことだと思う．')),
                ('ratemo_13', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='行動を決める時，直観に頼ることが多い．')),
                ('ratemo_14', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='私にとって，新しい考え方を学ぶことは，とても魅力的である．')),
                ('ratemo_15', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='複雑な問題を解決するのは，得意ではない．')),
                ('ratemo_16', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='知的な挑戦が好きだ．')),
                ('ratemo_17', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='直観に頼って重要な決定をするのは，いい考えだと思わない．')),
                ('ratemo_18', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='もし私が直観に頼るならば，間違いをおかすことが多くなるだろう．')),
                ('ratemo_19', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='直観的な印象に頼るのが好きだ．')),
                ('ratemo_20', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='一生懸命考えなければならないような問題を解決するのが好きだ．')),
                ('ratemo_21', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='答えを見つけるために直観に従って，うまくいかなかったことはほとんどない．')),
                ('ratemo_22', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='人生や生活上のいろんな問題を考えるとき，直観的にやるとうまくいく．')),
                ('ratemo_23', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='注意深く論理的な分析が必要とされる問題を解決するのは，得意ではない．')),
                ('ratemo_24', otree.db.models.StringField(choices=[('全くあてはまらない', '全くあてはまらない'), ('あまりあてはまらない', 'あまりあてはまらない'), ('どちらともいえない', 'どちらともいえない'), ('少しあてはまる', '少しあてはまる'), ('非常にあてはまる', '非常にあてはまる')], max_length=10000, null=True, verbose_name='いろいろ考えるのは好きではない．')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='REI.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rei_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rei_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REI.Subsession')),
            ],
            options={
                'db_table': 'REI_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REI.Subsession'),
        ),
    ]
