# Generated by Django 2.2.12 on 2021-05-23 05:03

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big5_group', to='otree.Session')),
            ],
            options={
                'db_table': 'BIG5_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='big5_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'BIG5_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('big5_1', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='活発で，外向的だと思う')),
                ('big5_2', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='他人に不満をもち，もめごとを起こしやすいと思う')),
                ('big5_3', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='しっかりしていて，自分に厳しいと思う')),
                ('big5_4', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='心配性で，うろたえやすいと思う')),
                ('big5_5', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='新しいことが好きで，変わった考えをもつと思う')),
                ('big5_6', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='ひかえめで，おとなしいと思う')),
                ('big5_7', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='人に気をつかう，やさしい人間だと思う')),
                ('big5_8', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='だらしなく，うっかりしていると思う')),
                ('big5_9', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='冷静で，気分が安定していると思う')),
                ('big5_10', otree.db.models.StringField(choices=[('1.全く違うと思う', '1.全く違うと思う'), ('2.おおよそ違うと思う', '2.おおよそ違うと思う'), ('3.少し違うと思う', '3.少し違うと思う'), ('4.どちらでもない', '4.どちらでもない'), ('5.少しそう思う', '5.少しそう思う'), ('6.まあまあそう思う', '6.まあまあそう思う'), ('7.強くそう思う', '7.強くそう思う')], max_length=10000, null=True, verbose_name='発想力に欠けた，平凡な人間だと思う')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BIG5.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big5_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big5_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BIG5.Subsession')),
            ],
            options={
                'db_table': 'BIG5_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BIG5.Subsession'),
        ),
    ]
