# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fw_disaster_group', to='otree.Session')),
            ],
            options={
                'db_table': 'FW_disaster_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('DisasterExp_1', otree.db.models.StringField(choices=[('経験し，大規模な被害を受けた', '経験し，大規模な被害を受けた'), ('経験し，被害を受けた', '経験し，被害を受けた'), ('経験し，小規模な被害を受けた', '経験し，小規模な被害を受けた'), ('経験したが，被害は全く受けなかった', '経験したが，被害は全く受けなかった'), ('経験したことはない', '経験したことはない')], max_length=10000, null=True, verbose_name='地震')),
                ('DisasterExp_2', otree.db.models.StringField(choices=[('経験し，大規模な被害を受けた', '経験し，大規模な被害を受けた'), ('経験し，被害を受けた', '経験し，被害を受けた'), ('経験し，小規模な被害を受けた', '経験し，小規模な被害を受けた'), ('経験したが，被害は全く受けなかった', '経験したが，被害は全く受けなかった'), ('経験したことはない', '経験したことはない')], max_length=10000, null=True, verbose_name='津波')),
                ('DisasterExp_3', otree.db.models.StringField(choices=[('経験し，大規模な被害を受けた', '経験し，大規模な被害を受けた'), ('経験し，被害を受けた', '経験し，被害を受けた'), ('経験し，小規模な被害を受けた', '経験し，小規模な被害を受けた'), ('経験したが，被害は全く受けなかった', '経験したが，被害は全く受けなかった'), ('経験したことはない', '経験したことはない')], max_length=10000, null=True, verbose_name='噴火')),
                ('DisasterExp_4', otree.db.models.StringField(choices=[('経験し，大規模な被害を受けた', '経験し，大規模な被害を受けた'), ('経験し，被害を受けた', '経験し，被害を受けた'), ('経験し，小規模な被害を受けた', '経験し，小規模な被害を受けた'), ('経験したが，被害は全く受けなかった', '経験したが，被害は全く受けなかった'), ('経験したことはない', '経験したことはない')], max_length=10000, null=True, verbose_name='土砂災害（崖崩れ・土石流・地滑り）')),
                ('DisasterExp_5', otree.db.models.StringField(choices=[('経験し，大規模な被害を受けた', '経験し，大規模な被害を受けた'), ('経験し，被害を受けた', '経験し，被害を受けた'), ('経験し，小規模な被害を受けた', '経験し，小規模な被害を受けた'), ('経験したが，被害は全く受けなかった', '経験したが，被害は全く受けなかった'), ('経験したことはない', '経験したことはない')], max_length=10000, null=True, verbose_name='豪雨')),
                ('DisasterExp_6', otree.db.models.StringField(choices=[('経験し，大規模な被害を受けた', '経験し，大規模な被害を受けた'), ('経験し，被害を受けた', '経験し，被害を受けた'), ('経験し，小規模な被害を受けた', '経験し，小規模な被害を受けた'), ('経験したが，被害は全く受けなかった', '経験したが，被害は全く受けなかった'), ('経験したことはない', '経験したことはない')], max_length=10000, null=True, verbose_name='洪水')),
                ('DisasterExp_7', otree.db.models.StringField(choices=[('経験し，大規模な被害を受けた', '経験し，大規模な被害を受けた'), ('経験し，被害を受けた', '経験し，被害を受けた'), ('経験し，小規模な被害を受けた', '経験し，小規模な被害を受けた'), ('経験したが，被害は全く受けなかった', '経験したが，被害は全く受けなかった'), ('経験したことはない', '経験したことはない')], max_length=10000, null=True, verbose_name='暴風・竜巻')),
                ('DisasterExp_8', otree.db.models.StringField(choices=[('経験し，大規模な被害を受けた', '経験し，大規模な被害を受けた'), ('経験し，被害を受けた', '経験し，被害を受けた'), ('経験し，小規模な被害を受けた', '経験し，小規模な被害を受けた'), ('経験したが，被害は全く受けなかった', '経験したが，被害は全く受けなかった'), ('経験したことはない', '経験したことはない')], max_length=10000, null=True, verbose_name='豪雪')),
                ('DisasterExp_9', otree.db.models.StringField(choices=[('経験し，大規模な被害を受けた', '経験し，大規模な被害を受けた'), ('経験し，被害を受けた', '経験し，被害を受けた'), ('経験し，小規模な被害を受けた', '経験し，小規模な被害を受けた'), ('経験したが，被害は全く受けなかった', '経験したが，被害は全く受けなかった'), ('経験したことはない', '経験したことはない')], max_length=10000, null=True, verbose_name='その他の異常な自然災害')),
                ('crt_HAP', otree.db.models.StringField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10000, null=True, verbose_name='あなたは現在，どの程度幸せですか？0-10満点で評価してください．')),
                ('crt_1st', otree.db.models.StringField(choices=[('あてはまらない', 'あてはまらない'), ('どちらかといえばあてはまらない', 'どちらかといえばあてはまらない'), ('どちらかといえばあてはまる', 'どちらかといえばあてはまる'), ('あてはまる', 'あてはまる')], max_length=10000, null=True, verbose_name='日常生活の中で，自分の行動は「自分自身」に見られていると思うことがある．')),
                ('crt_2nd', otree.db.models.StringField(choices=[('あてはまらない', 'あてはまらない'), ('どちらかといえばあてはまらない', 'どちらかといえばあてはまらない'), ('どちらかといえばあてはまる', 'どちらかといえばあてはまる'), ('あてはまる', 'あてはまる')], max_length=10000, null=True, verbose_name='日常生活の中で，自分の行動は「直接誰か（人間）」に見られていると思うことがある．')),
                ('crt_3rd', otree.db.models.StringField(choices=[('あてはまらない', 'あてはまらない'), ('どちらかといえばあてはまらない', 'どちらかといえばあてはまらない'), ('どちらかといえばあてはまる', 'どちらかといえばあてはまる'), ('あてはまる', 'あてはまる')], max_length=10000, null=True, verbose_name='日常生活の中で，自分の行動は「監視カメラ等を通じて誰か（人間）」に間接的に見られていると思うことがある．')),
                ('crt_sup', otree.db.models.StringField(choices=[('あてはまらない', 'あてはまらない'), ('どちらかといえばあてはまらない', 'どちらかといえばあてはまらない'), ('どちらかといえばあてはまる', 'どちらかといえばあてはまる'), ('あてはまる', 'あてはまる')], max_length=10000, null=True, verbose_name='日常生活の中で，自分の行動は「お天道様や神様，仏様などの超自然的な存在」に見られていると思うことがある．')),
                ('FW1', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='未来はいつも運命によって決められていると信じている')),
                ('FW2', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人の性格や才能は，（脳のつくりなどの）生物学的な構造によって決まっている')),
                ('FW3', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人の歴史の大部分は偶然の出来事の積み重ねである')),
                ('FW4', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人は自分の意志で決定を下すことができる')),
                ('FW5', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='どんなに努力しても，自分の運命は変えられない')),
                ('FW6', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='心理学者や精神科医はやがて人のふるまいの全てを解明するだろう')),
                ('FW7', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='誰もこれから起こることを予測できない')),
                ('FW8', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人は自分が下した誤った選択に対しては，一切の責任を負わなくてはならない')),
                ('FW9', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='全ての人の人生は，最初から運命によって決められている')),
                ('FW10', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='自分の将来は，遺伝子によって決められている')),
                ('FW11', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='サイコロの目やコイントスのように，人生は予測できない')),
                ('FW12', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人は心から望めば，どんな障害でも乗り越えられる')),
                ('FW13', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='物事はなるようにしかならず，自分にできることは少ない')),
                ('FW14', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='過去の経験がどのように現在の自分の知性や性格を形作ってきたかを，科学は示してくれる')),
                ('FW15', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人は誰しも予測できないようなふるまいをする')),
                ('FW16', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='犯罪者には自分の行った悪事に対する，全面的な責任がある')),
                ('FW17', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='その考え方が好きかどうかは別として，人生は説明できない力に動かされているように思う')),
                ('FW18', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人間の行動は他の動物たちと同じように，いつも自然の摂理に従っている')),
                ('FW19', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='日々の出来事は全くもって一貫性を持たないため，先を予測することは難しい')),
                ('FW20', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人生は運に負うところが大きい')),
                ('FW21', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人は自らの自由な意志や思考で行動している')),
                ('FW22', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='親の持つ性質は，子どもの性質を決めている')),
                ('FW23', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人は，自分のあやまちにいつも責任を負っている')),
                ('FW24', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='大人になってから成功するかは子どもの頃の環境で決まる')),
                ('FW25', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人に起こる出来事は，偶然の産物である')),
                ('FW26', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='精神力が強ければ，自分に生じた欲望をいつも抑えることができる')),
                ('FW27', otree.db.models.StringField(choices=[('1.そう思わない', '1.そう思わない'), ('2.どちらかといえばそう思わない', '2.どちらかといえばそう思わない'), ('3.どちらでもない', '3.どちらでもない'), ('4.どちらかといえばそう思う', '4.どちらかといえばそう思う'), ('5.そう思う', '5.そう思う')], max_length=10000, null=True, verbose_name='人の将来は予測することができない')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FW_disaster.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fw_disaster_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fw_disaster_player', to='otree.Session')),
            ],
            options={
                'db_table': 'FW_disaster_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fw_disaster_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'FW_disaster_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW_disaster.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW_disaster.Subsession'),
        ),
    ]
