# Generated by Django 2.2.4 on 2019-12-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otree', '0002_session_mturk_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitPagePassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix_time', models.PositiveIntegerField()),
                ('is_enter', models.BooleanField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otree.Participant')),
            ],
        ),
        migrations.DeleteModel(
            name='FailedSessionCreation',
        ),
        migrations.RemoveField(
            model_name='pagecompletion',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='session',
            name='_pre_create_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ready_for_browser',
        ),
        migrations.AddField(
            model_name='pagecompletion',
            name='unix_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waitpagepassage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otree.Session'),
        ),
    ]
