# Generated by Django 2.2.4 on 2019-12-19 14:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_country',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='あなたの出身国を教えて下さい.'),
        ),
    ]
