# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-22 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='HAPPINESS',
        ),
    ]
