# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svotree2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'svotree2_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('slider1', otree.db.models.FloatField(null=True)),
                ('slider2', otree.db.models.FloatField(null=True)),
                ('slider3', otree.db.models.FloatField(null=True)),
                ('slider4', otree.db.models.FloatField(null=True)),
                ('slider5', otree.db.models.FloatField(null=True)),
                ('slider6', otree.db.models.FloatField(null=True)),
                ('slider_angle', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('slider_classification', otree.db.models.StringField(max_length=10000, null=True)),
                ('slider7', otree.db.models.FloatField(null=True)),
                ('slider8', otree.db.models.FloatField(null=True)),
                ('slider9', otree.db.models.FloatField(null=True)),
                ('slider10', otree.db.models.FloatField(null=True)),
                ('slider11', otree.db.models.FloatField(null=True)),
                ('slider12', otree.db.models.FloatField(null=True)),
                ('slider13', otree.db.models.FloatField(null=True)),
                ('slider14', otree.db.models.FloatField(null=True)),
                ('slider15', otree.db.models.FloatField(null=True)),
                ('nine_item_tdm_1', otree.db.models.StringField(max_length=10000, null=True)),
                ('nine_item_tdm_2', otree.db.models.StringField(max_length=10000, null=True)),
                ('nine_item_tdm_3', otree.db.models.StringField(max_length=10000, null=True)),
                ('nine_item_tdm_4', otree.db.models.StringField(max_length=10000, null=True)),
                ('nine_item_tdm_5', otree.db.models.StringField(max_length=10000, null=True)),
                ('nine_item_tdm_6', otree.db.models.StringField(max_length=10000, null=True)),
                ('nine_item_tdm_7', otree.db.models.StringField(max_length=10000, null=True)),
                ('nine_item_tdm_8', otree.db.models.StringField(max_length=10000, null=True)),
                ('nine_item_tdm_9', otree.db.models.StringField(max_length=10000, null=True)),
                ('nine_item_tdm_prosocial', otree.db.models.IntegerField(null=True)),
                ('nine_item_tdm_individualistic', otree.db.models.IntegerField(null=True)),
                ('nine_item_tdm_competitive', otree.db.models.IntegerField(null=True)),
                ('nine_item_tdm_classification', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_1', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_2', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_3', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_4', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_5', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_6', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_7', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_8', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_9', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_10', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_11', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_12', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_13', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_14', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_15', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_16', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_17', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_18', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_19', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_20', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_21', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_22', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_23', otree.db.models.StringField(max_length=10000, null=True)),
                ('ring_measure_24', otree.db.models.StringField(max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='svotree2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svotree2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svotree2_player', to='otree.Session')),
            ],
            options={
                'db_table': 'svotree2_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svotree2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'svotree2_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svotree2.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svotree2.Subsession'),
        ),
    ]
